<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3.2 (Python 3.13.5 on win32)" generated="2025-07-12T15:43:37.200025" rpa="false" schemaversion="5">
<suite id="s1" name="Robo Alvo" source="C:\Users\HP\Music\VS Code\AutomacaoRF\robo_alvo.robot">
<test id="s1-t1" name="Teste que Propositalmente Falha" line="5">
<kw name="Log" owner="BuiltIn">
<msg time="2025-07-12T15:43:37.255367" level="INFO">Este teste foi desenhado para falhar.</msg>
<arg>Este teste foi desenhado para falhar.</arg>
<doc>Logs the given message with the given level.</doc>
<status status="PASS" start="2025-07-12T15:43:37.255199" elapsed="0.000247"/>
</kw>
<kw name="Directory Should Exist" owner="OperatingSystem">
<msg time="2025-07-12T15:43:37.255903" level="FAIL">Directory 'C:\diretorio\inexistente\para\teste' does not exist.</msg>
<arg>C:\\diretorio\\inexistente\\para\\teste</arg>
<doc>Fails unless the given path points to an existing directory.</doc>
<status status="FAIL" start="2025-07-12T15:43:37.255595" elapsed="0.000469">Directory 'C:\diretorio\inexistente\para\teste' does not exist.</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>Se esta mensagem aparecer, algo deu errado no plano.</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-07-12T15:43:37.256202" elapsed="0.000025"/>
</kw>
<status status="FAIL" start="2025-07-12T15:43:37.254372" elapsed="0.002014">Directory 'C:\diretorio\inexistente\para\teste' does not exist.</status>
</test>
<status status="FAIL" start="2025-07-12T15:43:37.201998" elapsed="0.054820"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Robo Alvo" id="s1" pass="0" fail="1" skip="0">Robo Alvo</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
